# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.cache/wt [current_project]
set_property parent.project_path /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.5 [current_project]
set_property ip_output_repo /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/imports/example_design/gt_rom_init_tx.dat
read_verilog -library xil_defaultlib {
  /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/new/counter.v
  /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/new/decoder.v
  /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/imports/example_design/gtwizard_0_gt_frame_gen.v
  /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/new/mux.v
  /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/imports/example_design/gtwizard_0_exdes.v
}
read_ip -quiet /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci
set_property used_in_implementation false [get_files -all /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xdc]
set_property used_in_implementation false [get_files -all /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/ip/gtwizard_0/gtwizard_0_ooc.xdc]
set_property is_locked true [get_files /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/constrs_1/imports/example_design/gtwizard_0_exdes.xdc
set_property used_in_implementation false [get_files /home/deki/Downloads/hsos/gtwizard_0_ex/gtwizard_0_ex.srcs/constrs_1/imports/example_design/gtwizard_0_exdes.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top gtwizard_0_exdes -part xc7k325tffg900-2


write_checkpoint -force -noxdef gtwizard_0_exdes.dcp

catch { report_utilization -file gtwizard_0_exdes_utilization_synth.rpt -pb gtwizard_0_exdes_utilization_synth.pb }
