################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 3.6
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : gtwizard_0_exdes.xdc
## /___/   / ## \   \  / ##  \___\/\___ ##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7k325t
## Package: ffg900
##
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
##
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.


################################## Clock Constraints ##########################


####################### GT reference clock constraints #########################


create_clock -period 8.000 [get_ports Q2_CLK0_GTREFCLK_PAD_P_IN]





create_clock -period 16.667 -name drpclk_in_i [get_ports DRP_CLK_IN_P]


# User Clock Constraints


set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/CLR}]
set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/D}]
################################# RefClk Location constraints #####################
set_property PACKAGE_PIN G8 [get_ports Q2_CLK0_GTREFCLK_PAD_P_IN]
set_property PACKAGE_PIN G7 [get_ports Q2_CLK0_GTREFCLK_PAD_N_IN]

## LOC constrain for DRP_CLK_P/N

## KC724 board constrain
# set_property LOC C25 [get_ports  DRP_CLK_IN_P]
# set_property LOC B25 [get_ports  DRP_CLK_IN_N]
## KC705 board constrain
set_property PACKAGE_PIN AD12 [get_ports DRP_CLK_IN_P]
set_property PACKAGE_PIN AD11 [get_ports DRP_CLK_IN_N]

################################# mgt wrapper constraints #####################

##---------- Set placement for gt0_gtx_wrapper_i/GTXE2_CHANNEL ------
set_property LOC GTXE2_CHANNEL_X0Y8 [get_cells gtwizard_0_support_i/inst/gtwizard_0_init_i/gtwizard_0_i/gt0_gtwizard_0_i/gtxe2_i]

##---------- Set ASYNC_REG for flop which have async input ----------
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_check*system_reset_r_reg}]

##---------- Set False Path from one clock to other ----------


set_property IOSTANDARD LVDS [get_ports DRP_CLK_IN_P]

set_property PACKAGE_PIN Y25 [get_ports rot_inca_in]
set_property PACKAGE_PIN Y26 [get_ports rot_incb_in]
set_property IOSTANDARD LVCMOS25 [get_ports rot_inca_in]
set_property IOSTANDARD LVCMOS25 [get_ports rot_incb_in]


#connect_debug_port u_ila_0/probe4 [get_nets [list gt0_frame_gen/state]]

connect_debug_port u_ila_0/probe0 [get_nets [list {gt0_frame_gen/deb_counter[0]} {gt0_frame_gen/deb_counter[1]} {gt0_frame_gen/deb_counter[2]} {gt0_frame_gen/deb_counter[3]} {gt0_frame_gen/deb_counter[4]} {gt0_frame_gen/deb_counter[5]} {gt0_frame_gen/deb_counter[6]} {gt0_frame_gen/deb_counter[7]} {gt0_frame_gen/deb_counter[8]} {gt0_frame_gen/deb_counter[9]} {gt0_frame_gen/deb_counter[10]} {gt0_frame_gen/deb_counter[11]} {gt0_frame_gen/deb_counter[12]} {gt0_frame_gen/deb_counter[13]} {gt0_frame_gen/deb_counter[14]} {gt0_frame_gen/deb_counter[15]} {gt0_frame_gen/deb_counter[16]} {gt0_frame_gen/deb_counter[17]} {gt0_frame_gen/deb_counter[18]} {gt0_frame_gen/deb_counter[19]}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list gtwizard_0_support_i/inst/gt_usrclk_source/txoutclk_mmcm0_i/gt0_txusrclk2_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 9 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {gt0_frame_gen/pwm_input_reg__0[0]} {gt0_frame_gen/pwm_input_reg__0[1]} {gt0_frame_gen/pwm_input_reg__0[2]} {gt0_frame_gen/pwm_input_reg__0[3]} {gt0_frame_gen/pwm_input_reg__0[4]} {gt0_frame_gen/pwm_input_reg__0[5]} {gt0_frame_gen/pwm_input_reg__0[6]} {gt0_frame_gen/pwm_input_reg__0[7]} {gt0_frame_gen/pwm_input_reg__0[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list rot_inca_in_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list rot_incb_in_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets gt0_txusrclk2_i]
